// Generated by nuxt-seo-utils
declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/vue/types'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/_robots.txt' | '/android-chrome-192x192.png' | '/android-chrome-512x512.png' | '/apple-touch-icon.png' | '/favicon-16x16.png' | '/favicon-32x32.png' | '/favicon.ico' | '/logo.png' | '/og-image.jpg' | '/site.webmanifest' | (string & Record<never, never>)
  type JsFiles = (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}

export {}
