// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/30/2025, 3:33:24 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ryantang/524studios/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ryantang/524studios/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ryantang/524studios/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ryantang/524studios/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ryantang/524studios/plugins/**/*.{js,ts,mjs}","/Users/ryantang/524studios/composables/**/*.{js,ts,mjs}","/Users/ryantang/524studios/utils/**/*.{js,ts,mjs}","/Users/ryantang/524studios/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ryantang/524studios/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ryantang/524studios/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ryantang/524studios/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;